/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/_onboarding'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingTourRouteImport } from './routes/_onboarding/tour'
import { Route as OnboardingSetupModeRouteImport } from './routes/_onboarding/setup-mode'
import { Route as OnboardingLocalSetupRouteImport } from './routes/_onboarding/local-setup'
import { Route as OnboardingCloudSetupRouteImport } from './routes/_onboarding/cloud-setup'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/_onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingTourRoute = OnboardingTourRouteImport.update({
  id: '/tour',
  path: '/tour',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingSetupModeRoute = OnboardingSetupModeRouteImport.update({
  id: '/setup-mode',
  path: '/setup-mode',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingLocalSetupRoute = OnboardingLocalSetupRouteImport.update({
  id: '/local-setup',
  path: '/local-setup',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingCloudSetupRoute = OnboardingCloudSetupRouteImport.update({
  id: '/cloud-setup',
  path: '/cloud-setup',
  getParentRoute: () => OnboardingRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/cloud-setup': typeof OnboardingCloudSetupRoute
  '/local-setup': typeof OnboardingLocalSetupRoute
  '/setup-mode': typeof OnboardingSetupModeRoute
  '/tour': typeof OnboardingTourRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/cloud-setup': typeof OnboardingCloudSetupRoute
  '/local-setup': typeof OnboardingLocalSetupRoute
  '/setup-mode': typeof OnboardingSetupModeRoute
  '/tour': typeof OnboardingTourRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_onboarding': typeof OnboardingRouteWithChildren
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_onboarding/cloud-setup': typeof OnboardingCloudSetupRoute
  '/_onboarding/local-setup': typeof OnboardingLocalSetupRoute
  '/_onboarding/setup-mode': typeof OnboardingSetupModeRoute
  '/_onboarding/tour': typeof OnboardingTourRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/settings'
    | '/login'
    | '/signup'
    | '/cloud-setup'
    | '/local-setup'
    | '/setup-mode'
    | '/tour'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/settings'
    | '/login'
    | '/signup'
    | '/cloud-setup'
    | '/local-setup'
    | '/setup-mode'
    | '/tour'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_onboarding'
    | '/profile'
    | '/settings'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_onboarding/cloud-setup'
    | '/_onboarding/local-setup'
    | '/_onboarding/setup-mode'
    | '/_onboarding/tour'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_onboarding': {
      id: '/_onboarding'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_onboarding/tour': {
      id: '/_onboarding/tour'
      path: '/tour'
      fullPath: '/tour'
      preLoaderRoute: typeof OnboardingTourRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_onboarding/setup-mode': {
      id: '/_onboarding/setup-mode'
      path: '/setup-mode'
      fullPath: '/setup-mode'
      preLoaderRoute: typeof OnboardingSetupModeRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_onboarding/local-setup': {
      id: '/_onboarding/local-setup'
      path: '/local-setup'
      fullPath: '/local-setup'
      preLoaderRoute: typeof OnboardingLocalSetupRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_onboarding/cloud-setup': {
      id: '/_onboarding/cloud-setup'
      path: '/cloud-setup'
      fullPath: '/cloud-setup'
      preLoaderRoute: typeof OnboardingCloudSetupRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface OnboardingRouteChildren {
  OnboardingCloudSetupRoute: typeof OnboardingCloudSetupRoute
  OnboardingLocalSetupRoute: typeof OnboardingLocalSetupRoute
  OnboardingSetupModeRoute: typeof OnboardingSetupModeRoute
  OnboardingTourRoute: typeof OnboardingTourRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingCloudSetupRoute: OnboardingCloudSetupRoute,
  OnboardingLocalSetupRoute: OnboardingLocalSetupRoute,
  OnboardingSetupModeRoute: OnboardingSetupModeRoute,
  OnboardingTourRoute: OnboardingTourRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
