/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VocabularyRouteImport } from './routes/vocabulary'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/_onboarding'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryIdRouteImport } from './routes/history.$id'
import { Route as OnboardingTourRouteImport } from './routes/_onboarding/tour'
import { Route as OnboardingLocalSetupRouteImport } from './routes/_onboarding/local-setup'
import { Route as OnboardingLocalProfileRouteImport } from './routes/_onboarding/local-profile'

const VocabularyRoute = VocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/_onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIdRoute = HistoryIdRouteImport.update({
  id: '/history/$id',
  path: '/history/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingTourRoute = OnboardingTourRouteImport.update({
  id: '/tour',
  path: '/tour',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingLocalSetupRoute = OnboardingLocalSetupRouteImport.update({
  id: '/local-setup',
  path: '/local-setup',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingLocalProfileRoute = OnboardingLocalProfileRouteImport.update({
  id: '/local-profile',
  path: '/local-profile',
  getParentRoute: () => OnboardingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/vocabulary': typeof VocabularyRoute
  '/local-profile': typeof OnboardingLocalProfileRoute
  '/local-setup': typeof OnboardingLocalSetupRoute
  '/tour': typeof OnboardingTourRoute
  '/history/$id': typeof HistoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/vocabulary': typeof VocabularyRoute
  '/local-profile': typeof OnboardingLocalProfileRoute
  '/local-setup': typeof OnboardingLocalSetupRoute
  '/tour': typeof OnboardingTourRoute
  '/history/$id': typeof HistoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_onboarding': typeof OnboardingRouteWithChildren
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/vocabulary': typeof VocabularyRoute
  '/_onboarding/local-profile': typeof OnboardingLocalProfileRoute
  '/_onboarding/local-setup': typeof OnboardingLocalSetupRoute
  '/_onboarding/tour': typeof OnboardingTourRoute
  '/history/$id': typeof HistoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/settings'
    | '/vocabulary'
    | '/local-profile'
    | '/local-setup'
    | '/tour'
    | '/history/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/settings'
    | '/vocabulary'
    | '/local-profile'
    | '/local-setup'
    | '/tour'
    | '/history/$id'
  id:
    | '__root__'
    | '/'
    | '/_onboarding'
    | '/profile'
    | '/settings'
    | '/vocabulary'
    | '/_onboarding/local-profile'
    | '/_onboarding/local-setup'
    | '/_onboarding/tour'
    | '/history/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  VocabularyRoute: typeof VocabularyRoute
  HistoryIdRoute: typeof HistoryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vocabulary': {
      id: '/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof VocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_onboarding': {
      id: '/_onboarding'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$id': {
      id: '/history/$id'
      path: '/history/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof HistoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_onboarding/tour': {
      id: '/_onboarding/tour'
      path: '/tour'
      fullPath: '/tour'
      preLoaderRoute: typeof OnboardingTourRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_onboarding/local-setup': {
      id: '/_onboarding/local-setup'
      path: '/local-setup'
      fullPath: '/local-setup'
      preLoaderRoute: typeof OnboardingLocalSetupRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_onboarding/local-profile': {
      id: '/_onboarding/local-profile'
      path: '/local-profile'
      fullPath: '/local-profile'
      preLoaderRoute: typeof OnboardingLocalProfileRouteImport
      parentRoute: typeof OnboardingRoute
    }
  }
}

interface OnboardingRouteChildren {
  OnboardingLocalProfileRoute: typeof OnboardingLocalProfileRoute
  OnboardingLocalSetupRoute: typeof OnboardingLocalSetupRoute
  OnboardingTourRoute: typeof OnboardingTourRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingLocalProfileRoute: OnboardingLocalProfileRoute,
  OnboardingLocalSetupRoute: OnboardingLocalSetupRoute,
  OnboardingTourRoute: OnboardingTourRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  VocabularyRoute: VocabularyRoute,
  HistoryIdRoute: HistoryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
